### ISSUE TITLE
Start over button not working

### ISSUE THREAD

**Issue by gallexi** [galantlex/comp-checkin#1]
I want to have a button to "start over" and reset the state of my form after a user has completed the workflow, so that the next user can come along and use essentially a fresh app. 

Here is the button:
https://github.com/galantlex/comp-checkin/blob/fe7b7ef268c7b72780b4dd81acfc5eb9223a646b/src/selectform.js#L71

And here is the function that I thought would work: 
https://github.com/galantlex/comp-checkin/blob/fe7b7ef268c7b72780b4dd81acfc5eb9223a646b/src/forms.js#L18-L20

Here's where I call the form in question:
https://github.com/galantlex/comp-checkin/blob/fe7b7ef268c7b72780b4dd81acfc5eb9223a646b/src/forms.js#L30

Right now the "Start Over" button does nothing at all on click, and I have yet to figure out why.

**Comment by JasonEtco** [comment]
@galantlex it looks like there's no `onClick` handler on the button. Should just be that simple ☂️ 

```js
 <button className="button is-primary" onClick={this.startOver}> Start Over </button> 
```

**Comment by gallexi** [comment]
You're right...I had tried that, and it didn't work then, but I'm not sure what I changed in the meantime, and now it works!! Thanks json @JasonEtco
